---
title: "Week 3: Statistical Models for Multivariate Analysis"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'week3.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    includes:
      in_header: "favicon.html"
---

## Weekly Objectives

  * Use linear regression in R to model continuous outcomes and be able to interpret its parameters
  * Use logistic regression in R to model binary outcomes and understand odds ratio and relative risk
  * Understand the logistic link and be able to interpret the parameter estimates in a logistic regression
  * Use R functions to evaluate model accuracy of a classification model
  * Understand the bias caused by censoring 
  * Use log-rank test and Cox proportional hazard model in R for survival outcomes
  
## Lecture Note

  + [[Statistical Tests](notes/week3/StatTesting.html){target='_blank'}]
  + The original `.Rmd` [`r xfun::embed_file('docs/notes/week3/StatTesting.Rmd', text = 'Source File')`] used to generate the lecture note
  + The [Cleveland Clinic Heart Disease Dataset](notes/week3/processed_cleveland.csv){target='_blank'} in `.csv` format. This data is also available on [Kaggle](https://www.kaggle.com/aavigan/cleveland-clinic-heart-disease-dataset)). 

## Homework

  + Reading: Finish Sections 5.5.4 from the [BPS textbook](info.html)
  + Finish the practice questions in the lecture note