---
title: "Week 5: TBL: Classification and Logistic Regression"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'week5.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    includes:
      in_header: "favicon.html"
---

## Weekly Objectives
  
  * Binary variables and Bernoulli distribution
  * Model the probability of a binary variable
  * Odds ratio and relative risk
  * The logistic link
  * Logistic regression
  * Interpreting parameters in a logistic regression
  * Testing the significance of a variable
  * Performing logistic regression in `R`
  * Dealing with categorical predictors
  * Measuring the model accuracy
  * The ROC curve and area under the curve (AUC)

## TBL Overview

You should **complete this reading material before** the TBL session on Wed, Aug 4. This week's TBL session focuses on calculating and interpreting some of the most popular quantities and models for disease frequencies. This includes odds ratio, relative risk and logistic regression. We will be using both simulated data and two papers: [McLaughlin et al. (2003)](notes/week5/papers/McLaughlin2003Extensive.pdf) and [O'Brien et al. (2020)](notes/week5/papers/OBrien2020Misplaced.pdf).

To successfully complete the questions in this TBL session, you should focus on the following topics while reading this material:

  * Use R to compute and interpret the relative risk, odds ratio and their confidence intervals
  * Apply the relative risk calculation to the data collected in [McLaughlin et al. (2003)](notes/week5/papers/McLaughlin2003Extensive.pdf)
  * Use R to perform logistic regression
  * Read the output from R to evaluate the variables and the overall model fitting
  * Interpreting the effects of variables in a logistic regression, using [O'Brien et al. (2020)](notes/week5/papers/OBrien2020Misplaced.pdf)
  * Use logistic regressions for prediction

There are also several questions about more advanced topics in linear regression:

  * Calculate and interpret the effect of categorical variables and their iterations in a logistic regression

## Reading Material

  * [[Relative Risk](notes/week5/TBL-RR.html)] [`.Rmd` `r xfun::embed_file('docs/notes/week5/TBL-RR.Rmd', text = 'Source File')`] 
  * [[Odds Ratio](notes/week5/TBL-OR.html)] [`.Rmd` `r xfun::embed_file('docs/notes/week5/TBL-OR.Rmd', text = 'Source File')`] 
  * [[Logistic Regression](notes/week5/TBL-Logistic.html)] [`.Rmd` `r xfun::embed_file('docs/notes/week5/TBL-Logistic.Rmd', text = 'Source File')`]
  * [Cleveland Heart Disease Data](notes/week5/processed_cleveland.csv)
  * [Sepsis Data](notes/week5/Sepsis.csv)
  
## Discussion Session

  * [[Model Evaluations](notes/week5/TBL-ModelEvaluation.html)] [`.Rmd` `r xfun::embed_file('docs/notes/week5/TBL-ModelEvaluation.Rmd', text = 'Source File')`] 