---
title: "Week 4: TBL: Correlation and Linear Regression"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'week4.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    includes:
      in_header: "favicon.html"
---

## Weekly Objectives
  
  * Independence and uncorrelated
  * Pearson correlation
  * Positive and negative correlation
  * Perform correlation calculation in R
  * Philosophy of linear regression
  * Perform linear regression in R
  * Interpretation of parameters
  * Testing for significance of parameter ($t$-test)
  * Testing for overall significance ($F$-test)
  * Model evaluation criteria
  
## TBL Overview

You should **complete this reading material before** the TBL session on Wed, July 28. This week's TBL session focuses on correlation and linear regression. To successfully complete the questions in this TBL session, you should focus on the following topics while reading the materials:

  * Use R to compute and interpret the correlation between two variables
  * Understand the relationship and differences between correlation and independence 
  * Use R to perform simple and multiple linear regressions
  * Read the output from R to evaluate the variables and the overall model fitting
  * How to use linear regression for prediction

There are also several questions about more advanced topics in linear regression:

  * What types of relationship cannot be properly modeled by a linear regression and how to address them in practice?
  * What is the risk and solutions of using too many variables in a linear regression
  * What is the effect of confounding variables

## Reading Material

  * [[Correlation and Independence](notes/week4/TBL-Correlation.html)]; Original `.Rmd` [`r xfun::embed_file('docs/notes/week4/TBL-Correlation.Rmd', text = 'Source File')`]
  * [[Simple Linear Regression](notes/week4/TBL-SLR.html)]; Original `.Rmd` [`r xfun::embed_file('docs/notes/week4/TBL-SLR.Rmd', text = 'Source File')`]
  * Multiple Linear Regression and Confounding Variables

## Discussion Session


